package ru.urururu.cmakeedit.core.checker;

import java.util.Arrays;
import java.util.List;

/**
 * Created by okutane on 22/08/16.
 */
public class Builtins {
    /** @see <a href='https://cmake.org/cmake/help/v3.0/manual/cmake-commands.7.html#normal-commands'>cmake help</a> */
    static List<String> NORMAL = Arrays.asList("add_compile_options",
            "add_custom_command",
            "add_custom_target",
            "add_definitions",
            "add_dependencies",
            "add_executable",
            "add_library",
            "add_subdirectory",
            "add_test",
            "aux_source_directory",
            "break",
            "build_command",
            "cmake_host_system_information",
            "cmake_minimum_required",
            "cmake_policy",
            "configure_file",
            "create_test_sourcelist",
            "define_property",
            "elseif",
            "else",
            "enable_language",
            "enable_testing",
            "endforeach",
            "endfunction",
            "endif",
            "endmacro",
            "endwhile",
            "execute_process",
            "export",
            "file",
            "find_file",
            "find_library",
            "find_package",
            "find_path",
            "find_program",
            "fltk_wrap_ui",
            "foreach",
            "function",
            "get_cmake_property",
            "get_directory_property",
            "get_filename_component",
            "get_property",
            "get_source_file_property",
            "get_target_property",
            "get_test_property",
            "if",
            "include_directories",
            "include_external_msproject",
            "include_regular_expression",
            "include",
            "install",
            "link_directories",
            "list",
            "load_cache",
            "load_command",
            "macro",
            "mark_as_advanced",
            "math",
            "message",
            "option",
            "project",
            "qt_wrap_cpp",
            "qt_wrap_ui",
            "remove_definitions",
            "return",
            "separate_arguments",
            "set_directory_properties",
            "set_property",
            "set",
            "set_source_files_properties",
            "set_target_properties",
            "set_tests_properties",
            "site_name",
            "source_group",
            "string",
            "target_compile_definitions",
            "target_compile_options",
            "target_include_directories",
            "target_link_libraries",
            "try_compile",
            "try_run",
            "unset",
            "variable_watch",
            "while",

            // added by hand
            "cmake_parse_arguments"
    );

    /** @see <a href='https://cmake.org/cmake/help/v3.0/manual/cmake-commands.7.html#deprecated-commands'>cmake help</a> */
    List<String> DEPRECATED = Arrays.asList("build_name",
            "exec_program",
            "export_library_dependencies",
            "install_files",
            "install_programs",
            "install_targets",
            "link_libraries",
            "make_directory",
            "output_required_files",
            "remove",
            "subdir_depends",
            "subdirs",
            "use_mangled_mesa",
            "utility_source",
            "variable_requires",
            "write_file");

    /** @see <a href='https://cmake.org/cmake/help/v3.0/manual/cmake-commands.7.html#ctest-commands'>cmake help</a> */
    List<String> CTEST = Arrays.asList("ctest_build",
            "ctest_configure",
            "ctest_coverage",
            "ctest_empty_binary_directory",
            "ctest_memcheck",
            "ctest_read_custom_files",
            "ctest_run_script",
            "ctest_sleep",
            "ctest_start",
            "ctest_submit",
            "ctest_test",
            "ctest_update",
            "ctest_upload");
}
